### ISSUE TITLE
Wrong constant used into disableWhiteChannel() method

### ISSUE THREAD

**Issue by mchobby** [sparkfun/SparkFun_VCNL4040_Arduino_Library#1]
I'm currently porting the library to MicroPython and noticed a typing error in the code.

The SparkFun_VCNL4040_Arduino_Library.cpp contains the following declaration:

```
void VCNL4040::disableWhiteChannel(void) {

  bitMask(VCNL4040_PS_MS, UPPER, VCNL4040_WHITE_EN_MASK, VCNL4040_WHITE_ENABLE);

}
```

The last constant in bitmask call should be **VCNL4040_WHITE_DISABLE**

Cheers,
Dominique

**Comment by nseidle** [comment]
Thanks for reporting. Did you know you can [link to line numbers](https://github.com/sparkfun/SparkFun_VCNL4040_Arduino_Library/blob/master/src/SparkFun_VCNL4040_Arduino_Library.cpp#L237)?

Good find! Fixed momentarily.
